--insert peoples
insert into people (id, name) values (1, 'Dru Winborn');
insert into people (id, name) values (2, 'Cyrille Meekin');
insert into people (id, name) values (3, 'Kassie Glaum');
insert into people (id, name) values (4, 'Marjory McAster');
insert into people (id, name) values (5, 'Richy Carek');
insert into people (id, name) values (6, 'Chloe Pizzey');
insert into people (id, name) values (7, 'Danny Downing');
insert into people (id, name) values (8, 'Andriana Woods');
insert into people (id, name) values (9, 'Ira Copcott');
insert into people (id, name) values (10, 'Deanne Worsnop');
insert into people (id, name) values (11, 'Sammie Cavy');
insert into people (id, name) values (12, 'Renee Pollok');
insert into people (id, name) values (13, 'Jameson Stoffersen');
insert into people (id, name) values (14, 'Cosimo Red');
insert into people (id, name) values (15, 'Jessica Enderle');
insert into people (id, name) values (16, 'Gus Klyner');
insert into people (id, name) values (17, 'Bree Boulde');
insert into people (id, name) values (18, 'Blancha Elmore');
insert into people (id, name) values (19, 'Basile Boyde');
insert into people (id, name) values (20, 'Tootsie Flewin');
insert into people (id, name) values (21, 'Tiffani Vassar');
insert into people (id, name) values (22, 'Maryjane Fitchew');
insert into people (id, name) values (23, 'Kirby Jehu');
insert into people (id, name) values (24, 'Annabelle Hegden');
insert into people (id, name) values (25, 'Brnaba Fildes');
insert into people (id, name) values (26, 'Lucille Malec');
insert into people (id, name) values (27, 'Hali Dominichelli');
insert into people (id, name) values (28, 'Broderic Hemeret');
insert into people (id, name) values (29, 'Trever Hill');
insert into people (id, name) values (30, 'Patrizio Kinastan');
insert into people (id, name) values (31, 'Perren Hunnicot');
insert into people (id, name) values (32, 'Daven Gobolos');
insert into people (id, name) values (33, 'Sandy Gambles');
insert into people (id, name) values (34, 'Bevvy Spriddle');
insert into people (id, name) values (35, 'Micheal Risdall');
insert into people (id, name) values (36, 'Margette Kee');
insert into people (id, name) values (37, 'Mimi Redman');
insert into people (id, name) values (38, 'Bjorn Becke');
insert into people (id, name) values (39, 'Alexandro Houldey');
insert into people (id, name) values (40, 'Sibilla Attle');
insert into people (id, name) values (41, 'Rockey Ainley');
insert into people (id, name) values (42, 'Nataniel Ralph');
insert into people (id, name) values (43, 'Rosie Soloway');
insert into people (id, name) values (44, 'Doreen Barenskie');
insert into people (id, name) values (45, 'Nanete Hembery');
insert into people (id, name) values (46, 'Bertram Bertolaccini');
insert into people (id, name) values (47, 'Wallas Lenton');
insert into people (id, name) values (48, 'Katrinka Gherardelli');
insert into people (id, name) values (49, 'Barty Badger');
insert into people (id, name) values (50, 'Terese Barker');
insert into people (id, name) values (51, 'Ondrea Petroff');
insert into people (id, name) values (52, 'Malachi Fancutt');
insert into people (id, name) values (53, 'Jo Serck');
insert into people (id, name) values (54, 'Clareta Ary');
insert into people (id, name) values (55, 'Jillane Turfin');
insert into people (id, name) values (56, 'Terry Perello');
insert into people (id, name) values (57, 'Amil Stubbins');
insert into people (id, name) values (58, 'Hettie Gisbey');
insert into people (id, name) values (59, 'Umberto Bradnum');
insert into people (id, name) values (60, 'Ruth Ivantyev');
insert into people (id, name) values (61, 'Marketa Palia');
insert into people (id, name) values (62, 'Catriona Balfour');
insert into people (id, name) values (63, 'Rivi Hearn');
insert into people (id, name) values (64, 'Zorana Springford');
insert into people (id, name) values (65, 'Fredia Isley');
insert into people (id, name) values (66, 'Zitella Bradd');
insert into people (id, name) values (67, 'Irwinn Euler');
insert into people (id, name) values (68, 'Leta Sammut');
insert into people (id, name) values (69, 'Georgianne McCraine');
insert into people (id, name) values (70, 'Donn Hawson');
insert into people (id, name) values (71, 'Faith Ducroe');
insert into people (id, name) values (72, 'Sianna Rainville');
insert into people (id, name) values (73, 'Mathilde Greder');
insert into people (id, name) values (74, 'Kimmy Haselwood');
insert into people (id, name) values (75, 'Aubree Bliben');
insert into people (id, name) values (76, 'Hilarius Gutridge');
insert into people (id, name) values (77, 'Emma Spirit');
insert into people (id, name) values (78, 'Woodman Littlejohns');
insert into people (id, name) values (79, 'Angie Flew');
insert into people (id, name) values (80, 'Clementia Abazi');
insert into people (id, name) values (81, 'Daphna Heskey');
insert into people (id, name) values (82, 'Prue Casely');
insert into people (id, name) values (83, 'Avictor Sander');
insert into people (id, name) values (84, 'Ephrem Arunowicz');
insert into people (id, name) values (85, 'Deana Ege');
insert into people (id, name) values (86, 'Lorry Lougheed');
insert into people (id, name) values (87, 'Cyb Camacke');
insert into people (id, name) values (88, 'Reggie Beviss');
insert into people (id, name) values (89, 'Courtenay Bodley');
insert into people (id, name) values (90, 'Deni Siemens');
insert into people (id, name) values (91, 'Manda Dewicke');
insert into people (id, name) values (92, 'Jefferson Casaroli');
insert into people (id, name) values (93, 'Eva Dubber');
insert into people (id, name) values (94, 'Yoshiko Lafferty');
insert into people (id, name) values (95, 'Kally Plumley');
insert into people (id, name) values (96, 'Frankie Swindley');
insert into people (id, name) values (97, 'Lacy MacColm');
insert into people (id, name) values (98, 'Bob Gemmell');
insert into people (id, name) values (99, 'Didi Ricks');
insert into people (id, name) values (100, 'Shanie Richichi');
insert into people (id, name) values (101, 'Marjory Wenderott');
insert into people (id, name) values (102, 'Virgie Charke');
insert into people (id, name) values (103, 'Bathsheba Jotham');
insert into people (id, name) values (104, 'Hilarius Pere');
insert into people (id, name) values (105, 'Jackqueline Clash');
insert into people (id, name) values (106, 'Leila Chelsom');
insert into people (id, name) values (107, 'Annalise Goodenough');
insert into people (id, name) values (108, 'Marketa Nys');
insert into people (id, name) values (109, 'Birk Dows');
insert into people (id, name) values (110, 'Sidney Allanby');
insert into people (id, name) values (111, 'Clemence O''Harney');
insert into people (id, name) values (112, 'Aldrich Kilpin');
insert into people (id, name) values (113, 'Antonia Yardley');
insert into people (id, name) values (114, 'Marjie Murty');
insert into people (id, name) values (115, 'Harlie Sebright');
insert into people (id, name) values (116, 'Jenna Gadie');
insert into people (id, name) values (117, 'Freida Petroselli');
insert into people (id, name) values (118, 'Vally Vaines');
insert into people (id, name) values (119, 'Horst Grzegorecki');
insert into people (id, name) values (120, 'Kaila Torrese');
insert into people (id, name) values (121, 'Nappie Farrah');
insert into people (id, name) values (122, 'Dalston Conibear');
insert into people (id, name) values (123, 'Marylynne Deaville');
insert into people (id, name) values (124, 'Gonzales Rowlings');
insert into people (id, name) values (125, 'Christean McLaughlan');
insert into people (id, name) values (126, 'Kirby Yaxley');
insert into people (id, name) values (127, 'Rosamund Bosomworth');
insert into people (id, name) values (128, 'Sherill Plom');
insert into people (id, name) values (129, 'Ferdinanda Hainge');
insert into people (id, name) values (130, 'Gretel Rumbold');
insert into people (id, name) values (131, 'Travers Mariet');
insert into people (id, name) values (132, 'Katey Thew');
insert into people (id, name) values (133, 'Niel Alyonov');
insert into people (id, name) values (134, 'Stevy Render');
insert into people (id, name) values (135, 'Eloise Panas');
insert into people (id, name) values (136, 'Gaelan Morratt');
insert into people (id, name) values (137, 'Agnola Rammell');
insert into people (id, name) values (138, 'Harper Antonetti');
insert into people (id, name) values (139, 'Hersh Sheffield');
insert into people (id, name) values (140, 'Kellyann Bahia');
insert into people (id, name) values (141, 'Haily Coast');
insert into people (id, name) values (142, 'Oneida Asquez');
insert into people (id, name) values (143, 'Barri Bortoloni');
insert into people (id, name) values (144, 'Missy Mobley');
insert into people (id, name) values (145, 'Arabella Tschierasche');
insert into people (id, name) values (146, 'Nana Hulle');
insert into people (id, name) values (147, 'Benedikta Algar');
insert into people (id, name) values (148, 'Ernest LeEstut');
insert into people (id, name) values (149, 'Harold Ivory');
insert into people (id, name) values (150, 'Marcellina Coppock.');
insert into people (id, name) values (151, 'Jeno McGurn');
insert into people (id, name) values (152, 'Helge Buche');
insert into people (id, name) values (153, 'Jasmin Warner');
insert into people (id, name) values (154, 'Krisha Hadgkiss');
insert into people (id, name) values (155, 'Mendel Ridger');
insert into people (id, name) values (156, 'Katherina Deehan');
insert into people (id, name) values (157, 'Torrance Semeniuk');
insert into people (id, name) values (158, 'Leeann Simkovitz');
insert into people (id, name) values (159, 'Rodge Imort');
insert into people (id, name) values (160, 'Flore Ennor');
insert into people (id, name) values (161, 'Leonard Fosdike');
insert into people (id, name) values (162, 'Bengt Moulsdall');
insert into people (id, name) values (163, 'Anni Batisse');
insert into people (id, name) values (164, 'Nana O''Hickey');
insert into people (id, name) values (165, 'Anatola Skarman');
insert into people (id, name) values (166, 'Kevan Ianizzi');
insert into people (id, name) values (167, 'Glori MacCrosson');
insert into people (id, name) values (168, 'Charlot Richter');
insert into people (id, name) values (169, 'Enrico Sayce');
insert into people (id, name) values (170, 'Tynan Robertot');
insert into people (id, name) values (171, 'Ilise Herity');
insert into people (id, name) values (172, 'Killian Bazley');
insert into people (id, name) values (173, 'Joete Wetwood');
insert into people (id, name) values (174, 'Lanni Westrope');
insert into people (id, name) values (175, 'Michele Filipic');
insert into people (id, name) values (176, 'Hedi Leaf');
insert into people (id, name) values (177, 'Arabella Kenwell');
insert into people (id, name) values (178, 'Talia Pelham');
insert into people (id, name) values (179, 'Petronella Tenpenny');
insert into people (id, name) values (180, 'Molly Poley');
insert into people (id, name) values (181, 'Tynan Skipton');
insert into people (id, name) values (182, 'Alard Jewiss');
insert into people (id, name) values (183, 'Wang Threadgill');
insert into people (id, name) values (184, 'Adrian Francescotti');
insert into people (id, name) values (185, 'Bancroft Hackforth');
insert into people (id, name) values (186, 'Anderson Christley');
insert into people (id, name) values (187, 'Allis Stobbie');
insert into people (id, name) values (188, 'Jamesy Oldam');
insert into people (id, name) values (189, 'Aldis Goshawk');
insert into people (id, name) values (190, 'Bondon Worssam');
insert into people (id, name) values (191, 'Drucy Malpas');
insert into people (id, name) values (192, 'Cassandra Kyffin');
insert into people (id, name) values (193, 'Jany Hazeldene');
insert into people (id, name) values (194, 'Felicle Pickburn');
insert into people (id, name) values (195, 'Milton Hauch');
insert into people (id, name) values (196, 'Kingsley Whelan');
insert into people (id, name) values (197, 'Neysa Boniface');
insert into people (id, name) values (198, 'Shana McBain');
insert into people (id, name) values (199, 'Horst Chedzoy');
insert into people (id, name) values (200, 'Alisa Colegrove');
insert into people (id, name) values (201, 'Lucas Rocha');

--Insert people type buyer
insert into buyer (people_type, id) values	(1,1);
insert into buyer (people_type, id) values	(1,2);
insert into buyer (people_type, id) values	(1,3);
insert into buyer (people_type, id) values	(1,4);
insert into buyer (people_type, id) values	(1,5);
insert into buyer (people_type, id) values	(1,6);
insert into buyer (people_type, id) values	(1,7);
insert into buyer (people_type, id) values	(1,8);
insert into buyer (people_type, id) values	(1,9);
insert into buyer (people_type, id) values	(1,10);
insert into buyer (people_type, id) values	(1,11);
insert into buyer (people_type, id) values	(1,12);
insert into buyer (people_type, id) values	(1,13);
insert into buyer (people_type, id) values	(1,14);
insert into buyer (people_type, id) values	(1,15);
insert into buyer (people_type, id) values	(1,16);
insert into buyer (people_type, id) values	(1,17);
insert into buyer (people_type, id) values	(1,18);
insert into buyer (people_type, id) values	(1,19);
insert into buyer (people_type, id) values	(1,20);
insert into buyer (people_type, id) values	(1,21);
insert into buyer (people_type, id) values	(1,22);
insert into buyer (people_type, id) values	(1,23);
insert into buyer (people_type, id) values	(1,24);
insert into buyer (people_type, id) values	(1,25);
insert into buyer (people_type, id) values	(1,26);
insert into buyer (people_type, id) values	(1,27);
insert into buyer (people_type, id) values	(1,28);
insert into buyer (people_type, id) values	(1,29);
insert into buyer (people_type, id) values	(1,30);
insert into buyer (people_type, id) values	(1,31);
insert into buyer (people_type, id) values	(1,32);
insert into buyer (people_type, id) values	(1,33);
insert into buyer (people_type, id) values	(1,34);
insert into buyer (people_type, id) values	(1,35);
insert into buyer (people_type, id) values	(1,36);
insert into buyer (people_type, id) values	(1,37);
insert into buyer (people_type, id) values	(1,38);
insert into buyer (people_type, id) values	(1,39);
insert into buyer (people_type, id) values	(1,40);
insert into buyer (people_type, id) values	(1,41);
insert into buyer (people_type, id) values	(1,42);
insert into buyer (people_type, id) values	(1,43);
insert into buyer (people_type, id) values	(1,44);
insert into buyer (people_type, id) values	(1,45);
insert into buyer (people_type, id) values	(1,46);
insert into buyer (people_type, id) values	(1,47);
insert into buyer (people_type, id) values	(1,48);
insert into buyer (people_type, id) values	(1,49);
insert into buyer (people_type, id) values	(1,50);
insert into buyer (people_type, id) values	(1,51);
insert into buyer (people_type, id) values	(1,52);
insert into buyer (people_type, id) values	(1,53);
insert into buyer (people_type, id) values	(1,54);
insert into buyer (people_type, id) values	(1,55);
insert into buyer (people_type, id) values	(1,56);
insert into buyer (people_type, id) values	(1,57);
insert into buyer (people_type, id) values	(1,58);
insert into buyer (people_type, id) values	(1,59);
insert into buyer (people_type, id) values	(1,60);
insert into buyer (people_type, id) values	(1,61);
insert into buyer (people_type, id) values	(1,62);
insert into buyer (people_type, id) values	(1,63);
insert into buyer (people_type, id) values	(1,64);
insert into buyer (people_type, id) values	(1,65);
insert into buyer (people_type, id) values	(1,66);
insert into buyer (people_type, id) values	(1,67);
insert into buyer (people_type, id) values	(1,68);
insert into buyer (people_type, id) values	(1,69);
insert into buyer (people_type, id) values	(1,70);
insert into buyer (people_type, id) values	(1,71);
insert into buyer (people_type, id) values	(1,72);
insert into buyer (people_type, id) values	(1,73);
insert into buyer (people_type, id) values	(1,74);
insert into buyer (people_type, id) values	(1,75);
insert into buyer (people_type, id) values	(1,76);
insert into buyer (people_type, id) values	(1,77);
insert into buyer (people_type, id) values	(1,78);
insert into buyer (people_type, id) values	(1,79);
insert into buyer (people_type, id) values	(1,80);
insert into buyer (people_type, id) values	(1,81);
insert into buyer (people_type, id) values	(1,82);
insert into buyer (people_type, id) values	(1,83);
insert into buyer (people_type, id) values	(1,84);
insert into buyer (people_type, id) values	(1,85);
insert into buyer (people_type, id) values	(1,86);
insert into buyer (people_type, id) values	(1,87);
insert into buyer (people_type, id) values	(1,88);
insert into buyer (people_type, id) values	(1,89);
insert into buyer (people_type, id) values	(1,90);
insert into buyer (people_type, id) values	(1,91);
insert into buyer (people_type, id) values	(1,92);
insert into buyer (people_type, id) values	(1,93);
insert into buyer (people_type, id) values	(1,94);
insert into buyer (people_type, id) values	(1,95);
insert into buyer (people_type, id) values	(1,96);
insert into buyer (people_type, id) values	(1,97);
insert into buyer (people_type, id) values	(1,98);
insert into buyer (people_type, id) values	(1,99);
insert into buyer (people_type, id) values	(1,100);


--Insert people type buyer
insert into seller (people_type, id) values	(2,101);
insert into seller (people_type, id) values	(2,102);
insert into seller (people_type, id) values	(2,103);
insert into seller (people_type, id) values	(2,104);
insert into seller (people_type, id) values	(2,105);
insert into seller (people_type, id) values	(2,106);
insert into seller (people_type, id) values	(2,107);
insert into seller (people_type, id) values	(2,108);
insert into seller (people_type, id) values	(2,109);
insert into seller (people_type, id) values	(2,110);
insert into seller (people_type, id) values	(2,111);
insert into seller (people_type, id) values	(2,112);
insert into seller (people_type, id) values	(2,113);
insert into seller (people_type, id) values	(2,114);
insert into seller (people_type, id) values	(2,115);
insert into seller (people_type, id) values	(2,116);
insert into seller (people_type, id) values	(2,117);
insert into seller (people_type, id) values	(2,118);
insert into seller (people_type, id) values	(2,119);
insert into seller (people_type, id) values	(2,120);
insert into seller (people_type, id) values	(2,121);
insert into seller (people_type, id) values	(2,122);
insert into seller (people_type, id) values	(2,123);
insert into seller (people_type, id) values	(2,124);
insert into seller (people_type, id) values	(2,125);
insert into seller (people_type, id) values	(2,126);
insert into seller (people_type, id) values	(2,127);
insert into seller (people_type, id) values	(2,128);
insert into seller (people_type, id) values	(2,129);
insert into seller (people_type, id) values	(2,130);
insert into seller (people_type, id) values	(2,131);
insert into seller (people_type, id) values	(2,132);
insert into seller (people_type, id) values	(2,133);
insert into seller (people_type, id) values	(2,134);
insert into seller (people_type, id) values	(2,135);
insert into seller (people_type, id) values	(2,136);
insert into seller (people_type, id) values	(2,137);
insert into seller (people_type, id) values	(2,138);
insert into seller (people_type, id) values	(2,139);
insert into seller (people_type, id) values	(2,140);
insert into seller (people_type, id) values	(2,141);
insert into seller (people_type, id) values	(2,142);
insert into seller (people_type, id) values	(2,143);
insert into seller (people_type, id) values	(2,144);
insert into seller (people_type, id) values	(2,145);
insert into seller (people_type, id) values	(2,146);
insert into seller (people_type, id) values	(2,147);
insert into seller (people_type, id) values	(2,148);
insert into seller (people_type, id) values	(2,149);
insert into seller (people_type, id) values	(2,150);
insert into seller (people_type, id) values	(2,151);
insert into seller (people_type, id) values	(2,152);
insert into seller (people_type, id) values	(2,153);
insert into seller (people_type, id) values	(2,154);
insert into seller (people_type, id) values	(2,155);
insert into seller (people_type, id) values	(2,156);
insert into seller (people_type, id) values	(2,157);
insert into seller (people_type, id) values	(2,158);
insert into seller (people_type, id) values	(2,159);
insert into seller (people_type, id) values	(2,160);
insert into seller (people_type, id) values	(2,161);
insert into seller (people_type, id) values	(2,162);
insert into seller (people_type, id) values	(2,163);
insert into seller (people_type, id) values	(2,164);
insert into seller (people_type, id) values	(2,165);
insert into seller (people_type, id) values	(2,166);
insert into seller (people_type, id) values	(2,167);
insert into seller (people_type, id) values	(2,168);
insert into seller (people_type, id) values	(2,169);
insert into seller (people_type, id) values	(2,170);
insert into seller (people_type, id) values	(2,171);
insert into seller (people_type, id) values	(2,172);
insert into seller (people_type, id) values	(2,173);
insert into seller (people_type, id) values	(2,174);
insert into seller (people_type, id) values	(2,175);
insert into seller (people_type, id) values	(2,176);
insert into seller (people_type, id) values	(2,177);
insert into seller (people_type, id) values	(2,178);
insert into seller (people_type, id) values	(2,179);
insert into seller (people_type, id) values	(2,180);
insert into seller (people_type, id) values	(2,181);
insert into seller (people_type, id) values	(2,182);
insert into seller (people_type, id) values	(2,183);
insert into seller (people_type, id) values	(2,184);
insert into seller (people_type, id) values	(2,185);
insert into seller (people_type, id) values	(2,186);
insert into seller (people_type, id) values	(2,187);
insert into seller (people_type, id) values	(2,188);
insert into seller (people_type, id) values	(2,189);
insert into seller (people_type, id) values	(2,190);
insert into seller (people_type, id) values	(2,191);
insert into seller (people_type, id) values	(2,192);
insert into seller (people_type, id) values	(2,193);
insert into seller (people_type, id) values	(2,194);
insert into seller (people_type, id) values	(2,195);
insert into seller (people_type, id) values	(2,196);
insert into seller (people_type, id) values	(2,197);
insert into seller (people_type, id) values	(2,198);
insert into seller (people_type, id) values	(2,199);
insert into seller (people_type, id) values	(2,200);
insert into seller (people_type, id) values	(2,201);